### PR TITLE
joinEager Fixes + $not Operator all with tests

### PR DESCRIPTION
**Pull request by Thomas-git**
Hello,

Here are fixes for joinEager queries when using mergeEager and pagination.
And another commit include the $not operator.
**UPDATE** Plus I added fixes for $select, $noSelect and graph queries we discussed in #97 

Hope this helps.

### CODE REVIEW

**Comment by dekelev** [comment]
Very nice PR @Thomas-git , thanks!

Can you please update the README? e.g. add the `$not` query operator.

Also, seems that this should be a major version release, right? if so and there are migration steps or important notes, you can add them at the bottom of the README page, above the other migration guides.

**Comment by Thomas-git** [comment]
You're right, that should be a major version, it can break existing code if assumption were made beyond what feathers query common stated.
I'll update the README accordingly.

**Comment by Thomas-git** [comment]
README updated. Please check for typo as English is not my mother tongue !

**Comment by dekelev** [comment]
Thank you! released in v6.0.0

**Pull request merged**
