### PR TITLE
Remove GroupBy for Find Count queries

### PR DESCRIPTION
**Pull request by gmercey**
An update for PR #150 as it wasn't clearing `groupBy` introduced by `$modify` queries

### CODE REVIEW

**Comment by gmercey** [comment]
It fixed the tests `params.modifierFiltersResults=true applies count from modify query` and `params.modifierFiltersResults=undefined applies count from modify query` as the query response for both tests was as follow :
```
{
  total: 1,
  limit: 2,
  skip: 0,
  data: [
    Company {
      id: 41,
      name: 'Google',
      ceo: 1,
      size: 'medium',
      jsonObject: null,
      jsonArray: null,
      jsonbObject: null,
      jsonbArray: null,
      employees: [Array]
    },
    Company {
      id: 42,
      name: 'Apple',
      ceo: null,
      size: 'large',
      jsonObject: null,
      jsonArray: null,
      jsonbObject: null,
      jsonbArray: null,
      employees: [Array]
    }
  ]
}
```

Clearing the `groupBy` for the count query fixes the issue

**Comment by dekelev** [comment]
Hi @alex-all3dp , can you please review this PR? it may break the behavior you've added [here](https://github.com/feathersjs-ecosystem/feathers-objection/commit/149e1d05dc68c5a7114049a278a37023e278cc5e).

@gmercey I'm reverting the previous PR until this PR is resolved.

**Comment by gmercey** [comment]
@alex-all3dp with which DB Engine do you get the error? Maybe we need to have different behaviour depending on the engine used?

**Comment by alex-all3dp** [comment]
> @alex-all3dp with which DB Engine do you get the error? Maybe we need to have different behaviour depending on the engine used?

@gmercey PostgreSQL

**Comment by gmercey** [comment]
We could wrap the `clear('groupBy)` around `if (params.modifierFiltersResults !== false)` to accommodate? Because the example you are giving is not a proper count query for pagination as it returns a non-aggregated column whereas the count query should return 1 value

**Comment by alex-all3dp** [comment]
> We could wrap the `clear('groupBy)` around `if (params.modifierFiltersResults !== false)` to accommodate? Because the example you are giving is not a proper count query for pagination as it returns a non-aggregated column whereas the count query should return 1 value

I guess that could work :)

**Comment by gmercey** [comment]
@dekelev @alex-all3dp PR updated

**Comment by alex-all3dp** [comment]
@gmercey The if clause does not fix the issue. My bad, I didn't look closely enough the first time.

So also without the if clause my find queries with modifiers still work as expected. The problem I am having on this branch is that `service.get` with a.modifier (`GET /entity/:id?$modify=myModifier`)  throws the error message. Any ideas?

**Comment by gmercey** [comment]
@alex-all3dp is it failing because the `service.get` is a wrapper for `_find` :
```
  _get (id, params = {}) {
    // merge user query with the 'id' to get
    const findQuery = Object.assign({}, { $and: [] }, params.query);
    findQuery.$and.push(this.getIdsQuery(id)); // BUG will fail with composite primary key because table name will be missing

    return this._find(Object.assign({}, params, { query: findQuery }))
      .then(page => {
        const data = page.data || page;

        if (data.length !== 1) {
          throw new errors.NotFound(`No record found for id '${id}'`);
        }

        return data[0];
      });
  }
```

What we should do in this case, is to pass `paginate=false` as a param because we don't care about pagination in that case.

**Pull request closed without merging**
